### ISSUE TITLE
Example code bug

### ISSUE THREAD

**Issue by JozefDropco** [swaechter/smbjwrapper#10]
Hi,
there is bug in your example code for custom SMBJ config.
`
SmbConfig smbConfig = SmbConfig.builder().withSoTimeout(3000).build();
AuthenticationContext authenticationContext = new AuthenticationContext("USERNAME", "PASSWORD".toCharArray(), "DOMAIN"**, smbConfig**);
try (SharedConnection sharedConnection = new SharedConnection("127.0.0.1", "Share", authenticationContext)) {
    // Do your work
}`

smbConfig should be passed to new SharedConnection instead

Kind regards,
Jozef

**Comment by swaechter** [comment]
Thank you very much. I also fixed two typos in the rename section.
