### ISSUE TITLE
Append new content to files

### ISSUE THREAD

**Issue by swaechter** [swaechter/smbjwrapper#14]
It should be possible to append content to existing files (and not overwrite them)

@JozefDropco Was your feature pull request released with the 0.9.1 release or is it still pending?

**Comment by JozefDropco** [comment]
Hi, it was included in 0.9.0 version but that version had an issue with
ClassCastException. 0.9.1 works

Dňa št 20. 12. 2018, 22:24 Simon Wächter <notifications@github.com>
napísal(a):

**Comment by swaechter** [comment]
Just implemented the feature. The flag for `getOutputStream(boolean)` alone doesn't work - the `CreateDisposition` has to be adjusted accordingly. See: https://msdn.microsoft.com/en-us/library/cc246502.aspx

Feel free to report any issues. I hope to implement the rename/session delay feature soon & make a proper 0.0.9 release
