### ISSUE TITLE
Add methods for retreiving File/Directory information

### ISSUE THREAD

**Issue by reisin1986** [swaechter/smbjwrapper#2]
Hi! I see, that there is no way to retreive file/directory information using only wrapper.
It would be great to create these methods for _FILE_ALL_INFORMATION or _FILE_BASIC_INFORMATION
In smbj exist methods like public FileAllInformation getFileInformation... but it is inconvenient to use these methods. 
What about it?

Sincerely,
Alex

**Comment by swaechter** [comment]
Hey Alex

Yes, that was on my TODO list. Am I right that you are looking for the following attributes:

* Creation Time
* Last Access Time
* Last Write Time
* Change Time
* File size

Maybe also:

* Check if the path is readable/writable

To be honest, I don't want to expose smbj objects, because the project should serve as a wrapper library, so I will expose these attributes via getter methods. Is that working for you?

Best,
Simon

**Comment by reisin1986** [comment]
Hi, Simon!
Yes - Creation Time,Last Access Time,Last Write Time,Change Time, File size - basic file information. 
Now I use my own methods like : 

`getSharedFileInformation(host, filename, username, password) 
                                                       .getBasicInformation()
                                                       .getChangeTime()
                                                       .toEpochMillis();`
But it's very uncomfortable - it would be great to add something like that into the wrapper.

Another issue I've bumped - usage of SmbConfig for setting up SMBClient - there are many important values such like timeouts, etc. 
But in current wrapper version we have only constructor for SharedConnection without possibility to setup SMBClient and it use  default configuration only.

Is it possible to do something about it?

Best, Alex

**Comment by swaechter** [comment]
Hi Alex

I just implemented all changes and made a 0.0.6 which should appear shortly in Maven.

You can find all changes here: https://github.com/swaechter/smbjwrapper/releases/tag/0.0.6

Can you test the release and give me some feedback? Feel free to request more features if you need any.

Best,
Simon

**Comment by reisin1986** [comment]
Hi! I've tested new methods - all works well!

**Comment by swaechter** [comment]
Hey, good to hear that :)
