### ISSUE TITLE
getting issue while file rename 

### ISSUE THREAD

**Issue by mohitissar** [swaechter/smbjwrapper#23]
com.hierynomu com.hierynomus.ms smb2.SMB ApiException: STATUS_ACCESS_DENIED (0xc0000022): SetInfo failed for SMB2FileId file rename. rename file

**Comment by swaechter** [comment]
Hey. Can you share a minimal reproducible example + a screenshot of the file permissions?

**Comment by mohitissar** [comment]
change in code working fine

        try (Directory directory = getDiskShare().openDirectory(getPath(), EnumSet.of(AccessMask.GENERIC_ALL), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null)) {
            //String newDirectoryPath = getParentPath().getPath() + PATH_SEPARATOR + newDirectoryName;
            String newDirectoryPath = getParentPath().getPath() + newDirectoryName;
            directory.rename(newDirectoryName, replaceIfExist);
            return new SmbDirectory(getSmbConnection(), newDirectoryPath);
        }

**Comment by swaechter** [comment]
Sorry I was too busy in the last two weeks, but I'll fix the other bug too and make a release today/tomorrow.

Best,
Simon
