### ISSUE TITLE
Problem with copyFileViaServerSideCopy.

### ISSUE THREAD

**Issue by isabsent** [swaechter/smbjwrapper#26]
I have forced to change `SMB2ShareAccess.ALL` to `EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ, SMB2ShareAccess.FILE_SHARE_DELETE)` when opening the `sourceFile` because of impossibility to remove the `sourceFile` after copying which leads to `STATUS_SHARING_VIOLATION (0xc0000043)`

    public void copyFileViaServerSideCopy(SmbFile destinationSmbFile) throws Buffer.BufferException, TransportException {
        try (
            File sourceFile = getDiskShare().openFile(getPath(), EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null);
            File destinationFile = getDiskShare().openFile(destinationSmbFile.getPath(), EnumSet.of(AccessMask.GENERIC_ALL), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OVERWRITE_IF, null);
        ) {
            sourceFile.remoteCopyTo(destinationFile);
        }
    }

**Comment by swaechter** [comment]
Hey thanks for reporting a bug and a workaround. Can you provide more information according to the issue template:

* Version of Java
* Version of smbj and smbjwrapper
* Version/type of your OS, e.g Linux x64 or Windows
* Version/type of the share you are testing against, e.g Windows SMB share, Linux Samba share, Synology share etc.
* Additional file permissions on the directories/files

The reason I ask: I tried to reproduce your problem with the following code (Which worked and deleted the source file):

```java
public class SmbTest {

    public static void main(String[] arguments) throws Exception {
        AuthenticationContext authenticationContext = new AuthenticationContext("SNIPPED", "SNIPPED".toCharArray(), "");
        try (SmbConnection smbConnection = new SmbConnection("127.0.0.1", "Share", authenticationContext)) {
            // Copy the file
            SmbFile sourceFile = new SmbFile(smbConnection, "StreetPermit.pdf");
            SmbFile destinationFile = new SmbFile(smbConnection, "StreetPermitCopied.pdf");
            sourceFile.copyFileViaServerSideCopy(destinationFile);

            // Delete the source file
            sourceFile.deleteFile();
            System.out.println("Does source file exist: " + sourceFile.isExisting());
        }
    }
}
```

**Comment by swaechter** [comment]
@isabsent Can you confirm that `EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ` also works (No FILE_SHARE_DELETE)?
