### ISSUE TITLE
[Proposal]: Add some methods to SmbOutputStream 

### ISSUE THREAD

**Issue by isabsent** [swaechter/smbjwrapper#27]
It would be nice to have two additional methods in your `SmbOutputStream`:

    @Override
    public void write(byte[] b) throws IOException {
        outputStream.write(b, 0, b.length);
    }

    @Override
    public void write(byte[] b, int off, int len) throws IOException {
        outputStream.write(b, off, len);
    }

**Comment by swaechter** [comment]
Thanks I'll try to add them this weekend + fix the bug you mentioned (Last weekend I ran into an OSSRH issue).

**Comment by isabsent** [comment]
What is the OSSRH issue?

**Comment by swaechter** [comment]
I think OSSRH started a new instance and I am on the old one. I had problem accessing the web interface on the old one + some web functionality didn't work afterwards. Guess I'll release via command line. Link: https://central.sonatype.org/publish/publish-guide/#deployment

```
Note: As of February 2021, all new projects began being provisioned on https://s01.oss.sonatype.org/. If your project is not provisioned on https://s01.oss.sonatype.org/, you will want to use the legacy host https://oss.sonatype.org/.
```

**Comment by swaechter** [comment]
I just added the methods you suggested with one change: `write(byte[] values, int offset, int length)` can only be used when `appendContent=false` (If set to true, it's always appended at the end of the file which would be wrong):

```java
    /**
     * Write a byte buffer to the SMB file. The values are appended if appendContent is set to true. Otherwise, they will overwrite the file.
     *
     * @param values Values to write or append
     * @throws IOException Exception in case of an IO/network problem
     */
    @Override
    public void write(byte[] values) throws IOException {
        outputStream.write(values, 0, values.length); // smbj ignores the offset when appending is enabled
    }

    /**
     * Write a byte buffer to the SMB file at a given offset with a given size. This method can only be used when appendContent is set to false.
     *
     * @param values Values to write
     * @param offset Offset in the file
     * @param length Length of the values to write
     * @throws IOException Exception in case of an IO/network problem
     */
    @Override
    public void write(byte[] values, int offset, int length) throws IOException {
        if (appendContent) {
            throw new IOException("The method SmbOutputStream.write(values, offset, length) can not be used when appendingContent is set to true.");
        }
        outputStream.write(values, offset, length);
    }
```

**Comment by swaechter** [comment]
The new `1.2.0` version should be available on Maven Central within the next 30 minutes.
