### ISSUE TITLE
Please support rang read and rang write.

### ISSUE THREAD

**Issue by s949492225** [swaechter/smbjwrapper#28]
Please support rang read and rang write.

This is very important, for example, the player plays the video switch progress

**Comment by swaechter** [comment]
Hi syiyi. What smbj code are you using for reading with an offset/length? Writing at a given position should be supported: via `SmbOutputStream.write(byte[] values, int offset, int length) throws IOException`: https://github.com/swaechter/smbjwrapper/blob/master/src/main/java/ch/swaechter/smbjwrapper/streams/SmbOutputStream.java#L74C5-L74C82
