### ISSUE TITLE
Feature request: add server side copy support

### ISSUE THREAD

**Issue by JozefDropco** [swaechter/smbjwrapper#4]
Hi, can you please add this feature into your wrapper. We would like to use this instead maintaining our own codebase for handling connections of SMBJ
Thanks and kind regards,
Jozef

**Comment by swaechter** [comment]
Hey Jozef

Yeah, that shouldn't be a problem. Can you share a working smbj example so I can base my work on? Are you aware of any problems like missing support in SMB version x or similar?

Best,
Simon

**Comment by JozefDropco** [comment]
Hi, its supported by SMB2 on. it was introduced into SMBJ recently in version 0.8.0. I made a draft of the functionality there but at the end it was refactored. 
https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/share/File.java

**public void remoteCopyTo(File destination) throws Buffer.BufferException, TransportException**

source file has to be opened for read and target for write of course

**Comment by swaechter** [comment]
Thank you very much. I just added a new method `SharedFile.copyFileViaServerSideCopy(SharedFile destinationSharedFile)` and made a `0.0.7-SNAPSHOT` release. You can get it from here: https://oss.sonatype.org/content/repositories/snapshots/ (Just add it as repository in Maven/Gradle).

Can you give me some feedback, so I can make a proper 0.0.7 release?

**Comment by swaechter** [comment]
@JozefDropco Were you able to test the feature?

**Comment by JozefDropco** [comment]
Hi,
sorry I forgot to respond. Yes it works. But maybe it would be better to open the source file with CreateDisposition OPEN as it might give false feeling to the user that the file was copied but instead there is an empty file. I think its better to fail fast then investigating why there is an empty file at the destination. Also it might be worth to use finally block to close the files as the handles might leak in case of any error

**Comment by swaechter** [comment]
Good point. I fixed it in commit 46f9983b198d6f60636bf08a8291d165e03159b7 and made a proper `0.0.7` release.

Are there other features you would like to see in the wrapper or things/documentation that should be improved?

**Comment by JozefDropco** [comment]
Hi,
I found this small issue
1. SharedConnection method close throws Exception which is too generic
IOException is enough

These features would be nice, we are using them
2.ShareDirectory
      - ensureExists(check isExisting if not create())
      - listFiles(pattern, recursive)
      - rename
3. SharedFile
      - getOutputStream(append) - new feature of SMBJ not yet released (I
made PR to SMBJ)
      - rename

and last one feature I have is recoverable outputstream. As OutputStream in
our application is opened for long time (sometimes even for hours) I have
to make sure I am able to write to the file even in case there was
connection closed/network issue etc. Combination of getOutputStream(append)
and some connection isClosed checking. Maybe similarly I will need to
create InputStream as it might also timeout/fail

st 26. 9. 2018 o 13:27 Simon Wächter <notifications@github.com> napísal(a):

**Comment by swaechter** [comment]
I just opened the issues and try to implement them in the next two weeks.

For `getOutputStream(boolean append)`: What is the exact use case for this feature? Isn't recreation the connection + a regular write an option? I guess keeping a connection that involves a lot of reconfiguration and other issues ;)

**Comment by JozefDropco** [comment]
Hi,
Unfortunately its not enough to reconnect and to regular write as it opens
the outpustream from offset 0 and overwrites the file from scratch. This
getOutputStream(append) will set the offset to size and starts writing at
the end of the file.

>>>>I guess keeping a connection that involves a lot of reconfiguration and
other issues ;)
This is useful: we have a long running ETL jobs which are logging into
files some information (keep alive messages for the business user - how
many records has been transferred). Sometimes it takes 3-5 hours to
complete - sometimes even more than 20 hours (due dataset size). We wouldnt
like to expose from code more than it should be. We are providing log
handler so it does log into server log and also the file log for the end
user. This log handler needs just a outputstream so we wrap the SMBJ
outputstream with custom reconnect code - which will reconnect if it got
disconnected in mean time.


po 8. 10. 2018 o 9:02 Simon Wächter <notifications@github.com> napísal(a):

**Comment by swaechter** [comment]
Hi Jozef

I just released version 0.0.8 with all the features/changes (Except the input stream append - I'll do that as soon as hierynomus/smbj#388 is in the next snapshot/release).

Your use case makes totally sense, I was just surprised that I never thought about that (I always create/rewrite files in our applications) - silly me

Simon
