### ISSUE TITLE
Add a list file method

### ISSUE THREAD

**Issue by swaechter** [swaechter/smbjwrapper#9]
Add a `SharedDirectory.listFiles(String searchPattern, boolean recursiveList)` method to [recursively] list files in a directory

@JozefDropco Are you in favor of a regex or a boolean supplier method (So you are able to filter more than file names, e.g. file size)? Both?

**Comment by JozefDropco** [comment]
Hi,
supplier method is just enough I think it gives more freedom to everyone

Kind regards,
Jozef

po 8. 10. 2018 o 8:42 Simon Wächter <notifications@github.com> napísal(a):
